routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group([
    'as' => 'admin.',
    'prefix' => 'admin'
], function () {
    Route::get('/login', 'Auth\AdminLoginController@loginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login.submit');
    Route::get('/', 'AdminsController@dashboard')->name('dashboard'); // this should come after
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('logout');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
});

Route::group([
    'prefix' => 'admin'
], function () {
    Route::resource('/financial_institutions', 'FinancialInstitutionsController');
    Route::resource('/cards', 'CardsController');
    Route::resource('/loans', 'LoansController');
    Route::resource('/articles', 'ArticlesController');
});

Route::get('/cards/{card}', 'CardsController@details')->name('cards.details');
Route::get('/loans/{loan}', 'LoansController@details')->name('loans.details');
Route::get('/articles/{article}', 'ArticlesController@details')->name('articles.details');

Route::get('/logout', 'Auth\LoginController@userLogout')->name('logout');
Route::get('/contact', 'StaticPagesController@contact');
Route::get('/about', 'StaticPagesController@about');

app/Loan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Loan extends Model
{
  public function loanType()
  {
    return $this->belongsTo(LoanType::class);
  }

  public function loanCategory()
  {
    return $this->belongsTo(LoanCategory::class);
  }

  public function repaymentOption()
  {
    return $this->hasMany(RepaymentOption::class);
  }
  
  protected $guarded = [];
}

app/LoanType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LoanType extends Model
{
  public function loanCategory()
  {
    return $this->hasOne(LoanCategory::class);
  }

  public function loan()
  {
    return $this->hasOne(Loan::class);
  }
}

app/Http/Controllers/LoansController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreLoan;
use App\Http\Requests\UpdateLoan;
use App\Loan;

class LoansController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin')->except('details'); // (auth:guard_name)
    }

    public function index()
    {
        $loans = Loan::orderBy('updated_at', 'desc')->paginate(20);

        return view('loans.index')->with('loans', $loans);
    }

    public function create()
    {
        return view('loans.create');
    }

    public function store(StoreLoan $request)
    {
        $loan = new Loan($request->all());
        $this->isAvailableToExpat($loan, $request);
        $loan->save();
        return redirect()->route('loans.show', ['id' => $loan->id]);
    }

    public function show($id)
    {
        $loan = Loan::find($id);
        return view('loans.show')->with('loan', $loan);
    }

    public function details($id)
    {
        $loan = Loan::find($id);
        return view('loans.details')->with('loan', $loan);
    }

    public function edit($id)
    {
        $loan = Loan::find($id);
        return view('loans.edit', compact('loan'));
    }

    public function update(UpdateLoan $request, $id)
    {
        $loan = Loan::find($id);
        $loan->update($request->all());
        $this->isAvailableToExpat($loan, $request);
        $loan->save();

        return redirect()->route('loans.show', ['id' => $loan->id]);
    }

    public function destroy($id)
    {
        $loan = Loan::find($id)->delete();
        return redirect()->route('loans.index');
    }

    private function isAvailableToExpat(Loan $loan, Request $request)
    {
        $availableToExpat = false;
        if ($request->has('is_available_to_expat')) {
            $availableToExpat = true;
        }

        $loan->is_available_to_expat = $availableToExpat;
    }
}

resources/views/loans/_form.blade.php
<form method="POST" action="{{ $action_path }}" enctype="multipart/form-data">
    {{ $method_field }}
    {{ csrf_field() }}

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" name="name" required value="{{ old('name',  isset($loan->name) ? $loan->name : null) }}">
    </div>

    <div class="form-group">
        <label for="slug">Slug</label>
        <input type="text" class="form-control" id="slug" name="slug" required value="{{ old('slug',  isset($loan->slug) ? $loan->slug : null) }}">
    </div>

    <div class="form-group">
        <label for="loan_type">Type</label>
        <select class="form-control" id="loan_type" name="loan_type_id" >
            @if (isset($loan->loan_type_id ))
                <option value="{{ $loan->loan_type_id }}">{{ $loan_types->find($loan->loan_type_id)->name }}</option>
                <option disabled="disabled">----------------</option>
            @endif
            @foreach ($loan_types as $type)
                <option value="{{ $type->id }}">{{ $type->name }}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group">
        <label for="loan_category">Category</label>
        <select class="form-control" id="loan_category" name="loan_category_id" >
            @if (isset($loan->loan_category_id))
                <option value="{{ $loan->loan_category_id }}">{{ $loan_categories->find($loan->loan_category_id)->name }}</option>
                <option disabled="disabled">----------------</option>
            @endif
            @foreach ($loan_categories as $category)
                <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group">
        <label for="max_credit_limit">Maximum Credit Limit</label>
        <input type="text" class="form-control" id="max_credit_limit" name="max_credit_limit" required value="{{ old('max_credit_limit',  isset($loan->max_credit_limit) ? $loan->max_credit_limit : null) }}">
    </div>

    <div class="form-group">
        <label for="benefit">Benefit</label>
        <textarea class="form-control" id="benefit" name="benefit" required>{{ old('benefit', isset($loan->benefit) ? $loan->benefit : null) }} </textarea>
    </div>

    <div class="form-group">
        <label for="detail">Detail</label>
        <textarea class="form-control" id="detail" name="detail" required>{{ old('detail', isset($loan->detail) ? $loan->detail : null) }} </textarea>
    </div>

    <div class="form-group">
        <label for="eligibility">Eligibility</label>
        <textarea class="form-control" id="eligibility" name="eligibility" required>{{ old('eligibility', isset($loan->eligibility) ? $loan->eligibility : null) }} </textarea>
    </div>

    <div class="form-group">
        <label for="document_required">Document Required</label>
        <textarea class="form-control" id="document_required" name="document_required" required>{{ old('document_required', isset($loan->document_required) ? $loan->document_required : null) }} </textarea>
    </div>

    <div class="checkbox">
      <label>
        <input type="checkbox" name="is_available_to_expat" value='1' {{ old('is_available_to_expat', isset($loan->is_available_to_expat) && $loan->is_available_to_expat === 1 ? 'checked' : '') }} > Available to Expat
      </label>
    </div>

    <button type="submit" class="btn btn-default">Submit</button>
</form>

resources/views/loans/_item-list.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="item-list">
            @foreach ($loans as $loan)
                <div class="col-md-12 item">
                    <a href="{{ route('loans.details', ['loan' => $loan->id]) }}">
                        <ul>
                            <div class="col-md-3">
                                <li><img src="{{ asset('no-image.png') }}" /></li>
                            </div>

                            <div class="col-md-9">
                                <div class="col-md-12 title">
                                    <li>{{ $loan->name }}</li>
                                    <hr>
                                </div>

                                <div class="col-md-2">
                                    <li>Type: {{ $loan_types->find($loan->loan_type_id)->name }}</li>
                                </div>

                                <div class="col-md-2">
                                    <li>Category: {{ $loan_categories->find($loan->loan_category_id)->name }}</li>
                                </div>

                                <div class="col-md-2">
                                    <li>Max: Credit Limit: {{ $loan->max_credit_limit }}</li>
                                </div>

                                <div class="col-md-3">
                                    <li>Min. Income: {{ $loan->min_income }}</li>
                                </div>

                                <div class="col-md-3 pull-right">
                                    <li>Updated: {{ $loan->updated_at->setTimezone('Asia/Bangkok')->diffForHumans() }}</li>
                                </div>

                                <div class="col-md-12">
                                    <br>
                                </div>

                                <div class="col-md-12 well">
                                    <li>Benefit: {{ $loan->benefit }}</li>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <hr>
                            </div>
                        </ul>
                    </a>
                </div>

            @endforeach
        </div>
    </div>
</div>

resources/views/loans/create.blade.php
@extends('layouts.admin')

@section('page_name', '- Create Loan')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include('layouts.errors')

            <h1>Create Loan</h1>
            <hr>

            @include('loans._form', [
                'action_path' => route('loans.store'),
                'method_field' => null,
            ])

        </div>
    </div>

@endsection

resources/views/loans/details.blade.php
@extends('layouts.main')

@section('page_name', '- {{ $loan->name }}')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include('layouts.errors')

            <h1>{{ $loan->name }}</h1>
            <hr>
            {{-- <p>{{ $loan->id }}</p>
            <p>{{ $loan->name }}</p>
            <p>{{ $loan_types->find($loan->loan_type_id)->name }}</p>
            <p>{{ $loan_categories->find($loan->loan_category_id)->name }}</p>
            <p>{{ $loan->max_credit_limit }}</p>
            <p>{{ $loan->updated_at->setTimezone('Asia/Bangkok')->format('d/M/Y h:i:s A') }}</p>
            <p> --}}
        </div>
    </div>
@endsection

resources/views/loans/edit.blade.php
@extends('layouts.admin')

@section('page_name', '- Edit Loan')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include('layouts.errors')

            <h1>Edit Loan</h1>
            <hr>

            @include('loans._form', [
                'action_path' => route('loans.update', ['loan' => $loan->id]),
                'method_field' => method_field('PUT'),
            ])

        </div>
    </div>

@endsection

resources/views/loans/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Manage Loans</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>

        <div class="x_content">
          <table id="datatable-checkbox" class="table table-striped bulk_action">
            <thead>
              <tr>

                {{-- <th><input type="checkbox" id="check-all" class="flat"></th> --}}
                <th>#ID</th>
                <th>Name</th>
                <th>Type</th>
                <th>Category</th>
                <th>Credit Limit</th>
                <th>Latest Update</th>
                <th>Action</th>
              </tr>
            </thead>

            @foreach ($loans as $loan)
                <tbody>
                  <tr>
                    {{-- <td>
                    <input type="checkbox" id="check-all" class="flat">
                    </td> --}}
                    <td>{{ $loan->id }}</td>
                    <td>{{ $loan->name }}</td>
                    <td>{{ $loan_types->find($loan->loan_type_id)->name }}</td>
                    <td>{{ $loan_categories->find($loan->loan_category_id)->name }}</td>
                    <td>{{ $loan->max_credit_limit }}</td>
                    <td>{{ $loan->updated_at->setTimezone('Asia/Bangkok')->format('d/M/Y h:i:s A') }}</td>
                    <td>
                        <form method="POST" action="{{ route('loans.update', ['loan' => $loan->id]) }}">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <a href="{{ route('loans.show', ['loan' => $loan->id]) }}" class="btn btn-info"><i class="fa fa-eye" ></i></a>
                            <a href="{{ route('loans.edit', ['loan' => $loan->id]) }}" class="btn btn-warning"><i class="fa fa-edit" ></i></a>
                            <button class="btn btn-danger" type="submit" ><i class="fa fa-trash" ></i></button>
                        </form>
                    </td>
                  </tr>
                </tbody>
            @endforeach
          </table>
          <div class="row">
              <div>Showing {{($loans->currentpage()-1)*$loans->perpage()+1}}-{{($loans->currentpage()-1)*$loans->perpage()+$loans->count()}} of {{$loans->total()}} entries
          </div>

          <div class="row">
              <div class="text-center" >{{ $loans->links() }}</div>
          </div>

            <div class="row">
                <p class="text-center"><a href="{{ route('loans.create') }}" class="btn btn-success"><i class="fa fa-plus" ></i> Create New Entry</a></p>
            </div>

        </div>
        </div>
      </div>
    </div>
@endsection

resources/views/loans/show.blade.php
@extends('layouts.admin')

@section('page_name', '- {{ $loan->name }}')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include('layouts.errors')

            <h1>{{ $loan->name }}</h1>
            <hr>
            <p>{{ $loan->id }}</p>
            <p>{{ $loan->name }}</p>
            <p>{{ $loan_types->find($loan->loan_type_id)->name }}</p>
            <p>{{ $loan_categories->find($loan->loan_category_id)->name }}</p>
            <p>{{ $loan->max_credit_limit }}</p>
            <p>{{ $loan->updated_at->setTimezone('Asia/Bangkok')->format('d/M/Y h:i:s A') }}</p>
            <p>

            <form method="POST" action="{{ route('loans.destroy', ['loan' => $loan->id]) }}">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}

                <a href="{{ route('loans.index') }}" class="btn btn-primary"><i class="fa fa-list-alt" ></i> Dashboard</a>
                <a href="{{ route('loans.edit', ['loan' => $loan->id]) }}" class="btn btn-warning"> <i class="fa fa-edit" ></i> Edit</a>
                <button type="submit" class="btn btn-danger" ><i class="fa fa-trash" ></i> Delete</button>
            </form>

        </div>
    </div>
@endsection