routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group([
    'as' => 'admin.',
    'prefix' => 'admin'
], function () {
    Route::get('/login', 'Auth\AdminLoginController@loginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login.submit');
    Route::get('/', 'AdminsController@dashboard')->name('dashboard'); // this should come after
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('logout');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
});

Route::group([
    'prefix' => 'admin'
], function () {
    Route::resource('/financial_institutions', 'FinancialInstitutionsController');
    Route::resource('/cards', 'CardsController');
    Route::resource('/loans', 'LoansController');
    Route::resource('/articles', 'ArticlesController');
});

Route::get('/cards/{card}', 'CardsController@details')->name('cards.details');
Route::get('/loans/{loan}', 'LoansController@details')->name('loans.details');
Route::get('/articles/{article}', 'ArticlesController@details')->name('articles.details');

Route::get('/logout', 'Auth\LoginController@userLogout')->name('logout');
Route::get('/contact', 'StaticPagesController@contact');
Route::get('/about', 'StaticPagesController@about');

app/FinancialInstitution.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FinancialInstitution extends Model
{
  public function fiCategory()
  {
    return $this->belongsTo(FICategory::class);
  }

  public function country()
  {
    return $this->belongsTo(Country::class);
  }

  protected $guarded = [];
}

app/Http/Controllers/FinancialInstitutionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\FinancialInstitution;
use App\Http\Requests\StoreFinancialInstitution;
use App\Http\Requests\UpdateFinancialInstitution;
use Image;

class FinancialInstitutionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin'); // (auth:guard_name)
    }

    public function index()
    {
        $fis = FinancialInstitution::orderBy('updated_at', 'desc')->paginate(20);

        return view('financial_institutions.index')->with('fis', $fis);
    }

    public function create()
    {
        return view('financial_institutions.create');
    }

    public function store(StoreFinancialInstitution $request)
    {
        $fi = new FinancialInstitution($request->except('logo'));
        $this->imageProcessing($fi, $request);
        $fi->save();
        return redirect('financial_institution.show', ['id' => $fi->id]);
    }

    public function show($id)
    {
        $fi = FinancialInstitution::find($id);
        return view('financial_institutions.show')->with('fi', $fi);
    }

    public function edit($id)
    {
        $fi = FinancialInstitution::find($id);
        return view('financial_institutions.edit')->with('fi', $fi);
    }

    public function update(UpdateFinancialInstitution $request, $id)
    {
        $fi = FinancialInstitution::find($id);
        $fi->update($request->except('logo'));
        $this->imageProcessing($fi, $request);
        $fi->save();
        return redirect()->route('financial_institutions.show', ['fi' => $fi->id]);
    }

    public function destroy($id)
    {
        $fi = FinancialInstitution::find($id);
        unlink(public_path('images/fi/logo/'.$fi->logo));
        $fi->delete();
        return redirect()->route('financial_institutions.index');
    }

    private function imageProcessing(FinancialInstitution $fi, Request $request)
    {
        if($request->hasFile('logo'))
        {
            if(isset($fi->logo))
            {
                $oldImage = $fi->logo;
                unlink(public_path('images/fi/logo/'.$oldImage));
            }
            $image = $request->file('logo');
            $filename = time().'.'.$image->getClientOriginalExtension();
            $image_location = public_path('images/fi/logo/'.$filename);
            Image::make($image)->resize(250, 200)->save($image_location);
            $fi->logo = $filename;
        }
    }

}

resources/views/financial_institutions/_form.blade.php
<form method="POST" action="{{ $action_path }}" enctype="multipart/form-data">
    {{ $method_field }}
    {{ csrf_field() }}

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" name="name" required value="{{ old('name',  isset($fi->name) ? $fi->name : null) }}">
    </div>

    <div class="form-group">
        <label for="fi_category">Category</label>
        <select class="form-control" id="fi_category" name="fi_category_id" >
            @if (isset($fi->fi_category_id))
                <option value="{{ $fi->fi_category_id }}">{{ $fi_categories->find($fi->fi_category_id)->name }}</option>
                <option disabled="disabled">----------------</option>
            @endif
            @foreach ($fi_categories as $category)
                <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group">
        <label for="address">Address</label>
        <input type="text" class="form-control" id="address" name="address" required value="{{ old('address',  isset($fi->address) ? $fi->address : null) }}">
    </div>

    <div class="form-group">
        <label for="city">City</label>
        <input type="text" class="form-control" id="city" name="city" required value="{{ old('city',  isset($fi->city) ? $fi->city : null) }}">
    </div>

    <div class="form-group">
        <label for="country">Country</label>
        <select class="form-control" id="country" name="country_id" >
            @if (isset($fi->country_id))
                <option value="{{ $fi->country_id }}">{{ $countries->find($fi->country_id)->name }}</option>
                <option disabled="disabled">----------------</option>
            @endif
            @foreach ($countries as $country)
                <option value="{{ $country->id }}">{{ $country->name }}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group">
        <label for="zipcode">Zipcode</label>
        <input type="text" class="form-control" id="zipcode" name="zipcode" required value="{{ old('zipcode',  isset($fi->zipcode) ? $fi->zipcode : null) }}">
    </div>

    <div class="form-group">
        <label for="website">Website</label>
        <input type="text" class="form-control" id="website" name="website" required value="{{ old('website',  isset($fi->website) ? $fi->website : null) }}">
    </div>

    <div class="form-group">
        <label for="phone_number">Phone Number</label>
        <input type="text" class="form-control" id="phone_number" name="phone_number" required value="{{ old('phone_number',  isset($fi->phone_number) ? $fi->phone_number : null) }}">
    </div>

    <div class="form-group">
        <label for="logo">Logo</label>
        <input type="file" class="form-control" id="logo" name="logo">
    </div>

    <button type="submit" class="btn btn-default">Submit</button>
</form>

resources/views/financial_institutions/create.blade.php
@extends('layouts.admin')

@section('page_name', '- Create New Financial Institution')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include('layouts.errors')

            <h1>Create New Financial Institution</h1>
            <hr>

            @include('financial_institutions._form', [
                'action_path' => route('financial_institutions.store'),
                'method_field' => null,
            ])

        </div>
    </div>

@endsection

resources/views/financial_institutions/edit.blade.php
@extends('layouts.admin')

@section('page_name', '- Edit Financial Institution')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include('layouts.errors')

            <h1>Edit Financial Institution</h1>
            <hr>

            @include('financial_institutions._form', [
                'action_path' => route('financial_institutions.update', ['financial_institutions' => $fi->id]),
                'method_field' => method_field('PUT'),
            ])

        </div>
    </div>

@endsection

resources/views/financial_institutions/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Manage Financial Institutions</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>

        <div class="x_content">
          <table id="datatable-checkbox" class="table table-striped bulk_action">
            <thead>
              <tr>

                {{-- <th><input type="checkbox" id="check-all" class="flat"></th> --}}
                <th>#ID</th>
                <th>Logo</th>
                <th>Name</th>
                <th>Category</th>
                <th>City</th>
                <th>Country</th>
                <th>Website</th>
                <th>Phone Number</th>
                <th>Latest Update</th>
                <th>Action</th>
              </tr>
            </thead>

            @foreach ($fis as $fi)
                <tbody>
                  <tr>
                    {{-- <td>
                    <input type="checkbox" id="check-all" class="flat">
                    </td> --}}
                    <td>{{ $fi->id }}</td>
                    <td><img src="{{ $fi->logo != null ? asset('images/fi/logo/'.$fi->logo) : asset('no-image.png')}}" height="100px" width="150px" /></td>
                    <td>{{ $fi->name }}</td>
                    <td>{{ $fi_categories->find($fi->fi_category_id)->name }}</td>
                    <td>{{ $fi->city }}</td>
                    <td>{{ $countries->find($fi->country_id)->name }}</td>
                    <td>{{ $fi->website }}</td>
                    <td>{{ $fi->phone_number }}</td>
                    <td>{{ $fi->updated_at->setTimezone('Asia/Bangkok')->format('d/M/Y h:i:s A') }}</td>
                    <td>
                        <form method="POST" action="{{ route('financial_institutions.update', ['financial_institution' => $fi->id]) }}">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <a href="{{ route('financial_institutions.show', ['financial_institution' => $fi->id]) }}" class="btn btn-info"><i class="fa fa-eye" ></i></a>
                            <a href="{{ route('financial_institutions.edit', ['financial_institution' => $fi->id]) }}" class="btn btn-warning"><i class="fa fa-edit" ></i></a>
                            <button class="btn btn-danger" type="submit" ><i class="fa fa-trash" ></i></button>
                        </form>
                    </td>
                  </tr>
                </tbody>
            @endforeach
          </table>
          <div class="row">
              <div>Showing {{($fis->currentpage()-1)*$fis->perpage()+1}}-{{($fis->currentpage()-1)*$fis->perpage()+$fis->count()}} of {{$fis->total()}} entries
          </div>

          <div class="row">
              <div class="text-center" >{{ $fis->links() }}</div>
          </div>

            <div class="row">
                <p class="text-center"><a href="{{ route('financial_institutions.create') }}" class="btn btn-success"><i class="fa fa-plus" ></i> Create New Entry</a></p>
            </div>

        </div>
        </div>
      </div>
    </div>
@endsection

resources/views/financial_institutions/show.blade.php
@extends('layouts.admin')

@section('page_name', '- {{$fi->name }}')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include('layouts.errors')

            <h1>{{ $fi->name }}</h1>
            <hr>

            <p>{{ $fi->id }}</p>
            <p><img src="{{ $fi->logo != null ? asset('images/fi/logo/'.$fi->logo) : asset('no-image.png')}}" height="100px" width="150px" /></p>
            <p>{{ $fi->name }}</p>
            <p>{{ $fi_categories->find($fi->fi_category_id)->name }}</p>
            <p>{{ $fi->address }}</p>
            <p>{{ $fi->city }}</p>
            <p>{{ $countries->find($fi->country_id)->name }}</p>
            <p>{{ $fi->website }}</p>
            <p>{{ $fi->phone_number }}</p>
            <p>{{ $fi->updated_at->setTimezone('Asia/Bangkok')->format('d/M/Y h:i:s A') }}</p>
            <p>

            <form method="POST" action="{{ route('articles.destroy', ['article' => $fi->id]) }}">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}

                <a href="{{ route('articles.index') }}" class="btn btn-primary"><i class="fa fa-list-alt" ></i> Dashboard</a>
                <a href="{{ route('articles.edit', ['article' => $fi->id]) }}" class="btn btn-warning"> <i class="fa fa-edit" ></i> Edit</a>
                <button type="submit" class="btn btn-danger" ><i class="fa fa-trash" ></i> Delete</button>
            </form>

        </div>
    </div>
@endsection