routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group([
    'as' => 'admin.',
    'prefix' => 'admin'
], function () {
    Route::get('/login', 'Auth\AdminLoginController@loginForm')->name('login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('login.submit');
    Route::get('/', 'AdminsController@dashboard')->name('dashboard'); // this should come after
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('logout');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
});

Route::group([
    'prefix' => 'admin'
], function () {
    Route::resource('/financial_institutions', 'FinancialInstitutionsController');
    Route::resource('/cards', 'CardsController');
    Route::resource('/loans', 'LoansController');
    Route::resource('/articles', 'ArticlesController');
});

Route::get('/cards/{card}', 'CardsController@details')->name('cards.details');
Route::get('/loans/{loan}', 'LoansController@details')->name('loans.details');
Route::get('/articles/{article}', 'ArticlesController@details')->name('articles.details');

Route::get('/logout', 'Auth\LoginController@userLogout')->name('logout');
Route::get('/contact', 'StaticPagesController@contact');
Route::get('/about', 'StaticPagesController@about');

app/Card.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Card extends Model
{
  public function cardType()
  {
    return $this->belongsTo(CardType::class);
  }

  public function cardTier()
  {
    return $this->belongsTo(CardTier::class);
  }

  public function coBrand()
  {
    return $this->belongsTo(coBrand::class);
  }

  protected $guarded = [];
}

app/CardType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CardType extends Model
{
  public function card()
  {
    return $this->hasMany(Card::class);
  }
}

app/Http/Controllers/CardsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreCard;
use App\Http\Requests\UpdateCard;
use App\Card;
use Image;

class CardsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin')->except('details'); // (auth:guard_name)
    }

    public function index()
    {
        $cards = Card::orderBy('updated_at', 'desc')->paginate(10);
        return view('cards.index')->with('cards', $cards);
    }


    public function create()
    {
        return view('cards.create');
    }

    public function store(StoreCard $request)
    {
        $card = new Card($request->except('image'));
        $this->imageProcessing($card, $request);
        $this->isAvailableToExpat($card, $request);
        $this->isCashCard($card, $request);
        $card->save();
        return redirect()->route('cards.show', ['id' => $card->id]);
    }


    public function show($id)
    {
        $card = Card::find($id);
        return view('cards.show')->with('card', $card);
    }

    public function details($id)
    {
        $card = Card::find($id);
        return view('cards.details')->with('card', $card);
    }

    public function edit($id)
    {
        $card = Card::find($id);
        return view('cards.edit')->with('card', $card);
    }


    public function update(UpdateCard $request, $id)
    {
        $card = Card::find($id);
        $card->update($request->except('image'));
        $this->imageProcessing($card, $request);
        $this->isAvailableToExpat($card, $request);
        $this->isCashCard($card, $request);
        $card->save();
        return redirect()->route('cards.show', ['id' => $card->id]);
    }

    public function destroy($id)
    {
        $card = Card::find($id);
        $this->removeImage($card);
        $card->delete();
        return redirect()->route('cards.index');
    }

    private function imageProcessing(Card $card, Request $request)
    {
        if($request->hasFile('image'))
        {
            $this->removeImage($card);

            $image = $request->file('image');
            $filename = time().'.'.$image->getClientOriginalExtension();
            $image_location = public_path('images/card/'.$filename);
            Image::make($image)->resize(250, 200)->save($image_location);
            $card->image = $filename;
        }
    }

    private function removeImage(Card $card)
    {
        if(isset($card->image))
        {
            unlink(public_path('images/card/'.$card->image));
        }
    }

    private function isAvailableToExpat(Card $card, Request $request)
    {
        $availableToExpat = false;
        if ($request->has('is_available_to_expat')) {
            $availableToExpat = true;
        }
        $card->is_available_to_expat = $availableToExpat;
    }

    private function isCashCard(Card $card, Request $request)
    {
        $availableToExpat = false;
        if ($request->has('is_cash_card')) {
            $availableToExpat = true;
        }
        $card->is_cash_card = $availableToExpat;
    }
}

resources/views/cards/_form.blade.php
<form method="POST" action="{{ $action_path }}" enctype="multipart/form-data">
    {{ $method_field }}
    {{ csrf_field() }}

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" name="name" required value="{{ old('name',  isset($card->name) ? $card->name : null) }}">
    </div>

    <div class="form-group">
        <label for="slug">Slug</label>
        <input type="text" class="form-control" id="slug" name="slug" required value="{{ old('slug',  isset($card->slug) ? $card->slug : null) }}">
    </div>

    <div class="checkbox">
      <label>
        <input type="checkbox" name="is_cash_card" value='1' {{ old('is_cash_card', isset($card->is_cash_card) && $card->is_cash_card === 1 ? 'checked' : '') }} > This is Cash Card
      </label>
    </div>

    <div class="form-group">
        <label for="card_type">Type</label>
        <select class="form-control" id="card_type" name="card_type_id" >
            @if (isset($card->card_type_id ))
                <option value="{{ $card->card_type_id }}">{{ $card_types->find($card->card_type_id)->name }}</option>
                <option disabled="disabled">----------------</option>
            @endif
            @foreach ($card_types as $type)
                <option value="{{ $type->id }}">{{ $type->name }}</option>
            @endforeach
        </select>
    </div>


    <div class="form-group">
        <label for="card_tier">Tier</label>
        <select class="form-control" id="card_tier" name="card_tier_id" >
            @if (isset($card->card_tier_id ))
                <option value="{{ $card->card_tier_id }}">{{ $card_tiers->find($card->card_tier_id)->name }}</option>
                <option disabled="disabled">----------------</option>
            @endif
            @foreach ($card_tiers as $tier)
                <option value="{{ $tier->id }}">{{ $tier->name }}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group">
        <label for="benefit">Benefit</label>
        <textarea class="form-control" id="benefit" name="benefit" required>{{ old('benefit', isset($card->benefit) ? $card->benefit : null) }} </textarea>
    </div>

    <div class="form-group">
        <label for="detail">Detail</label>
        <textarea class="form-control" id="detail" name="detail" required>{{ old('detail', isset($card->detail) ? $card->detail : null) }} </textarea>
    </div>

    <div class="form-group">
        <label for="reward_redemption">Reward Redemption</label>
        <textarea class="form-control" id="reward_redemption" name="reward_redemption" required>{{ old('reward_redemption', isset($card->reward_redemption) ? $card->reward_redemption : null) }} </textarea>
    </div>

    <div class="form-group">
        <label for="eligibility">Eligibility</label>
        <textarea class="form-control" id="eligibility" name="eligibility" required>{{ old('eligibility', isset($card->eligibility) ? $card->eligibility : null) }} </textarea>
    </div>

    <div class="form-group">
        <label for="document_required">Document Required</label>
        <textarea class="form-control" id="document_required" name="document_required" required>{{ old('document_required', isset($card->document_required) ? $card->document_required : null) }} </textarea>
    </div>

    <div class="form-group">
        <label for="min_age">Minimum Age</label>
        <input type="text" class="form-control" id="min_age" name="min_age" required value="{{ old('min_age',  isset($card->min_age) ? $card->min_age : null) }}">
    </div>

    <div class="form-group">
        <label for="min_income">Minimum Income</label>
        <input type="text" class="form-control" id="min_income" name="min_income" required value="{{ old('min_income',  isset($card->min_income) ? $card->min_income : null) }}">
    </div>

    <div class="form-group">
        <label for="min_repayment">Minimum Repayment</label>
        <input type="text" class="form-control" id="min_repayment" name="min_repayment" required value="{{ old('min_repayment',  isset($card->min_repayment) ? $card->min_repayment : null) }}">
    </div>

    <div class="form-group">
        <label for="interest_free_period">Interest Free Period</label>
        <input type="text" class="form-control" id="interest_free_period" name="interest_free_period" required value="{{ old('interest_free_period',  isset($card->interest_free_period) ? $card->interest_free_period : null) }}">
    </div>

    <div class="form-group">
        <label for="new_entry_fee_prime">New Entry Fee (Primary Card)</label>
        <input type="text" class="form-control" id="new_entry_fee_prime" name="new_entry_fee_prime" required value="{{ old('new_entry_fee_prime',  isset($card->new_entry_fee_prime) ? $card->new_entry_fee_prime : null) }}">
    </div>

    <div class="form-group">
        <label for="new_entry_fee_add">New Entry Fee (Supplementary Card)</label>
        <input type="text" class="form-control" id="new_entry_fee_add" name="new_entry_fee_add" required value="{{ old('new_entry_fee_add',  isset($card->new_entry_fee_add) ? $card->new_entry_fee_add : null) }}">
    </div>

    <div class="form-group">
        <label for="annual_fee_prime">Annual Fee (Primary Card)</label>
        <input type="text" class="form-control" id="annual_fee_prime" name="annual_fee_prime" required value="{{ old('annual_fee_prime',  isset($card->annual_fee_prime) ? $card->annual_fee_prime : null) }}">
    </div>

    <div class="form-group">
        <label for="annual_fee_add">Annual Fee (Supplementary Card)</label>
        <input type="text" class="form-control" id="annual_fee_add" name="annual_fee_add" required value="{{ old('annual_fee_add',  isset($card->annual_fee_add) ? $card->annual_fee_add : null) }}">
    </div>


    <div class="form-group">
        <label for="misc_fee">Misc Fee</label>
        <textarea class="form-control" id="misc_fee" name="misc_fee" required>{{ old('misc_fee', isset($card->misc_fee) ? $card->misc_fee : null) }} </textarea>
    </div>

    <div class="checkbox">
      <label>
        <input type="checkbox" name="is_available_to_expat" value='1' {{ old('is_available_to_expat', isset($card->is_available_to_expat) && $card->is_available_to_expat === 1 ? 'checked' : '') }} > Available to Expat
      </label>
    </div>

    <div class="form-group">
        <label for="image">Image</label>
        <input type="file" class="form-control" id="image" name="image">
    </div>

    <button type="submit" class="btn btn-default">Submit</button>
</form>

resources/views/cards/_item-list.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="item-list">
            @foreach ($cards as $card)
                <div class="col-md-12 item">
                    <a href="{{ route('cards.details', ['card' => $card->id]) }}">
                        <ul>
                            <div class="col-md-3">
                                <li><img src="{{ $card->image != null ? asset('images/card/'.$card->image) : asset('no-image.png')}}" /></li>
                            </div>

                            <div class="col-md-9">
                                <div class="col-md-12 title">
                                    <li>{{ $card->name }}</li>
                                    <hr>
                                </div>

                                <div class="col-md-2">
                                    <li>{{ $card_types->find($card->card_type_id)->name }}</li>
                                </div>

                                <div class="col-md-2">
                                    <li>{{ $card_tiers->find($card->card_tier_id)->name }}</li>
                                </div>

                                <div class="col-md-2">
                                    <li>Min. Age: {{ $card->min_age }}</li>
                                </div>

                                <div class="col-md-3">
                                    <li>Min. Income: {{ $card->min_income }}</li>
                                </div>

                                <div class="col-md-3 pull-right">
                                    <li>Updated: {{ $card->updated_at->setTimezone('Asia/Bangkok')->diffForHumans() }}</li>
                                </div>

                                <div class="col-md-12">
                                    <br>
                                </div>

                                <div class="col-md-12 well">
                                    <li>Benefit: {{ $card->benefit }}</li>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <hr>
                            </div>
                        </ul>
                    </a>
                </div>

            @endforeach
        </div>
    </div>
</div>

resources/views/cards/create.blade.php
@extends('layouts.admin')

@section('page_name', '- Create Card')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include('layouts.errors')

            <h1>Create Card</h1>
            <hr>

            @include('cards._form', [
                'action_path' => route('cards.store'),
                'method_field' => null,
            ])

        </div>
    </div>

@endsection

resources/views/cards/details.blade.php
@extends ('layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include('layouts.errors')

            <h1>{{ $card->name }}</h1>
            <hr>
            <p>{{ $card->id }}</p>

            <p>{{ $card_types->find($card->card_type_id)->name }}</p>
            <p>{{ $card_tiers->find($card->card_tier_id)->name }}</p>
            <p>{{ $card->max_credit_limit }}</p>
            <p>{{ $card->updated_at->setTimezone('Asia/Bangkok')->format('d/M/Y h:i:s A') }}</p>
            <p>


        </div>
    </div>
@endsection

resources/views/cards/edit.blade.php
@extends('layouts.admin')

@section('page_name', '- Edit Card')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include('layouts.errors')

            <h1>Edit Card</h1>
            <hr>

            @include('cards._form', [
                'action_path' => route('cards.update', ['card' => $card->id]),
                'method_field' => method_field('PUT'),
            ])

        </div>
    </div>

@endsection

resources/views/cards/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Manage Cards</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>

        <div class="x_content">
          <table id="datatable-checkbox" class="table table-striped bulk_action">
            <thead>
              <tr>

                {{-- <th><input type="checkbox" id="check-all" class="flat"></th> --}}
                <th>#ID</th>
                <th>Image</th>
                <th>Name</th>
                <th>Tier</th>
                <th>Cash Card</th>
                <th>Latest Update</th>
                <th>Action</th>
              </tr>
            </thead>

            @foreach ($cards as $card)
                <tbody>
                  <tr>
                    {{-- <td>
                    <input type="checkbox" id="check-all" class="flat">
                    </td> --}}
                    <td>{{ $card->id }}</td>
                    <td><img src="{{ $card->image != null ? asset('images/card/'.$card->image) : asset('no-image.png')}}" height="100px" width="150px" /></td>
                    <td>{{ $card->name }}</td>
                    <td>{{ $card_tiers->find($card->card_tier_id)->name }}</td>
                    <td>{{ $card->is_cash_card }}</td>
                    <td>{{ $card->updated_at->setTimezone('Asia/Bangkok')->format('d/M/Y h:i:s A') }}</td>
                    <td>
                        <form method="POST" action="{{ route('cards.update', ['card' => $card->id]) }}">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <a href="{{ route('cards.show', ['card' => $card->id]) }}" class="btn btn-info"><i class="fa fa-eye" ></i></a>
                            <a href="{{ route('cards.edit', ['card' => $card->id]) }}" class="btn btn-warning"><i class="fa fa-edit" ></i></a>
                            <button class="btn btn-danger" type="submit" ><i class="fa fa-trash" ></i></button>
                        </form>
                    </td>
                  </tr>
                </tbody>
            @endforeach
          </table>
          <div class="row">
              <div>Showing {{($cards->currentpage()-1)*$cards->perpage()+1}}-{{($cards->currentpage()-1)*$cards->perpage()+$cards->count()}} of {{$cards->total()}} entries
          </div>

          <div class="row">
              <div class="text-center" >{{ $cards->links() }}</div>
          </div>

            <div class="row">
                <p class="text-center"><a href="{{ route('cards.create') }}" class="btn btn-success"><i class="fa fa-plus" ></i> Create New Entry</a></p>
            </div>
        </div>

        </div>
      </div>
    </div>
@endsection

resources/views/cards/show.blade.php
@extends('layouts.admin')

@section('page_name', '- {{ $card->name }}')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include('layouts.errors')

            <h1>{{ $card->name }}</h1>
            <hr>
            <p>{{ $card->id }}</p>

            {{-- <p>{{ $card_types->find($card->card_type_id)->name }}</p>
            <p>{{ $card_categories->find($card->card_category_id)->name }}</p>
            <p>{{ $card->max_credit_limit }}</p>
            <p>{{ $card->updated_at->setTimezone('Asia/Bangkok')->format('d/M/Y h:i:s A') }}</p>
            <p> --}}

            <form method="POST" action="{{ route('cards.destroy', ['card' => $card->id]) }}">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}

                <a href="{{ route('cards.index') }}" class="btn btn-primary"><i class="fa fa-list-alt" ></i> Dashboard</a>
                <a href="{{ route('cards.edit', ['card' => $card->id]) }}" class="btn btn-warning"> <i class="fa fa-edit" ></i> Edit</a>
                <button type="submit" class="btn btn-danger" ><i class="fa fa-trash" ></i> Delete</button>
            </form>

        </div>
    </div>
@endsection